"""initial schema

Revision ID: 066cf68194cc
Revises: b9011b35fb39
Create Date: 2026-09-17 16:23:19.470767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066cf68194cc'
down_revision = 'b9011b35fb39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_window_days', sa.Integer(), nullable=False),
    sa.Column('deduction_enabled', sa.Boolean(), nullable=False),
    sa.Column('deduction_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shopify_customer_id', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_shopify_customer_id'), ['shopify_customer_id'], unique=True)

    op.create_table('otp_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('resend_count', sa.Integer(), nullable=True),
    sa.Column('consumed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_tokens_email'), ['email'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shopify_order_id', sa.String(length=64), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('PREPAID', 'COD', name='paymentmethod'), nullable=False),
    sa.Column('financial_status', sa.String(length=32), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_shopify_order_id'), ['shopify_order_id'], unique=True)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('shopify_line_item_id', sa.String(length=64), nullable=False),
    sa.Column('shopify_variant_id', sa.String(length=64), nullable=True),
    sa.Column('shopify_product_id', sa.String(length=64), nullable=True),
    sa.Column('product_title', sa.String(length=255), nullable=False),
    sa.Column('size', sa.String(length=32), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_number', sa.String(length=20), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('requested_size', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Enum('SIZE_TOO_SMALL', 'SIZE_TOO_LARGE', 'DAMAGED', 'OTHER', name='exchangereason'), nullable=False),
    sa.Column('reason_other_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PICKUP_SCHEDULED', 'PARCEL_RECEIVED', 'COMPLETED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('rejected_stage', sa.String(length=16), nullable=True),
    sa.Column('rejection_reason', sa.Enum('TAGS_REMOVED', 'ITEM_USED_WORN', 'OUTSIDE_RETURN_WINDOW', 'DAMAGE_NOT_MANUFACTURING', 'PHOTOS_INCONCLUSIVE', 'SUSPECTED_FRAUD', 'OTHER', name='rejectionreason'), nullable=True),
    sa.Column('rejection_note', sa.Text(), nullable=True),
    sa.Column('pickup_carrier', sa.String(length=32), nullable=True),
    sa.Column('pickup_tracking_id', sa.String(length=64), nullable=True),
    sa.Column('pickup_status', sa.String(length=32), nullable=True),
    sa.Column('outbound_carrier', sa.String(length=32), nullable=True),
    sa.Column('outbound_tracking_id', sa.String(length=64), nullable=True),
    sa.Column('outbound_status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('photo_decision_at', sa.DateTime(), nullable=True),
    sa.Column('parcel_received_at', sa.DateTime(), nullable=True),
    sa.Column('parcel_decision_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exchange_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_requests_exchange_number'), ['exchange_number'], unique=True)

    op.create_table('return_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_number', sa.String(length=20), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('SIZE_ISSUE', 'QUALITY_ISSUE', 'WRONG_ITEM_RECEIVED', 'DAMAGED', 'NOT_AS_DESCRIBED', 'CHANGED_MIND', 'OTHER', name='returnreason'), nullable=False),
    sa.Column('reason_other_text', sa.Text(), nullable=True),
    sa.Column('photo_urls', sa.JSON(), nullable=True),
    sa.Column('refund_mode', sa.Enum('ACCOUNT', 'GIFT_CARD', name='refundmode'), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deduction_applied', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_refund_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gift_card_code', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PICKUP_SCHEDULED', 'PARCEL_RECEIVED', 'COMPLETED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('rejected_stage', sa.String(length=16), nullable=True),
    sa.Column('rejection_reason', sa.Enum('TAGS_REMOVED', 'ITEM_USED_WORN', 'OUTSIDE_RETURN_WINDOW', 'DAMAGE_NOT_MANUFACTURING', 'PHOTOS_INCONCLUSIVE', 'SUSPECTED_FRAUD', 'OTHER', name='rejectionreason'), nullable=True),
    sa.Column('rejection_note', sa.Text(), nullable=True),
    sa.Column('pickup_carrier', sa.String(length=32), nullable=True),
    sa.Column('pickup_tracking_id', sa.String(length=64), nullable=True),
    sa.Column('pickup_status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('photo_decision_at', sa.DateTime(), nullable=True),
    sa.Column('parcel_received_at', sa.DateTime(), nullable=True),
    sa.Column('parcel_decision_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('return_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_requests_return_number'), ['return_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_requests_return_number'))

    op.drop_table('return_requests')
    with op.batch_alter_table('exchange_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_requests_exchange_number'))

    op.drop_table('exchange_requests')
    op.drop_table('order_items')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_shopify_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))

    op.drop_table('orders')
    with op.batch_alter_table('otp_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_tokens_email'))

    op.drop_table('otp_tokens')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_shopify_customer_id'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))

    op.drop_table('customers')
    op.drop_table('admin_settings')
    # ### end Alembic commands ###
